当前 恐龙袋袋 直播已结束
ERROR: insert live share url https://v.douyin.com/ik3E2V6A/ failed (0, '')
ERROR: Failed download stream file (0, '')
Exception in thread Thread-169 (run):
Traceback (most recent call last):
  File "/usr/local/python312/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/local/python312/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/main/CodeSpace/Project/SocialMediaStreamDownloader/./backend/src/platform/douyin/douyin_live_downloader.py", line 458, in run
    raise e
  File "/mnt/main/CodeSpace/Project/SocialMediaStreamDownloader/./backend/src/platform/douyin/douyin_live_downloader.py", line 433, in run
    self.database.insert_live_share_url_record(record_tuple)
  File "/mnt/main/CodeSpace/Project/SocialMediaStreamDownloader/backend/src/platform/douyin/douyin_share_url_database.py", line 139, in insert_live_share_url_record
    raise e
  File "/mnt/main/CodeSpace/Project/SocialMediaStreamDownloader/backend/src/platform/douyin/douyin_share_url_database.py", line 96, in insert_live_share_url_record
    cursor.execute(sql)
  File "/mnt/main/CodeSpace/Project/SocialMediaStreamDownloader/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/mnt/main/CodeSpace/Project/SocialMediaStreamDownloader/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/mnt/main/CodeSpace/Project/SocialMediaStreamDownloader/venv/lib/python3.12/site-packages/pymysql/connections.py", line 562, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/mnt/main/CodeSpace/Project/SocialMediaStreamDownloader/venv/lib/python3.12/site-packages/pymysql/connections.py", line 843, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')
